"""added table classi

Revision ID: 2ed15fc3bb9e
Revises: 6d907f89c162
Create Date: 2023-02-05 15:22:06.418981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed15fc3bb9e'
down_revision = '6d907f89c162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anno_corso', sa.SmallInteger(), nullable=True),
    sa.Column('sezione', sa.String(length=1), nullable=True),
    sa.Column('anno_scolastico', sa.Integer(), nullable=True),
    sa.Column('ordine', sa.String(length=255), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classi')
    # ### end Alembic commands ###
