"""added table alunni

Revision ID: 410d0173cac6
Revises: 932866b18727
Create Date: 2023-02-05 15:29:44.571958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410d0173cac6'
down_revision = '932866b18727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunni')
    # ### end Alembic commands ###
