"""added table genitori

Revision ID: 8c44d73c09bb
Revises: ac65fad1dbbe
Create Date: 2023-02-05 15:33:56.350155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c44d73c09bb'
down_revision = 'ac65fad1dbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genitori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genitori')
    # ### end Alembic commands ###
