"""added table anagrafiche

Revision ID: 932866b18727
Revises: 4832d47e8aba
Create Date: 2023-02-05 15:26:52.208354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932866b18727'
down_revision = '4832d47e8aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anagrafiche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cf', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('cognome', sa.String(length=64), nullable=True),
    sa.Column('data_nascita', sa.Date(), nullable=True),
    sa.Column('sesso', sa.Boolean(), nullable=True),
    sa.Column('civico', sa.SmallInteger(), nullable=True),
    sa.Column('via', sa.String(length=255), nullable=True),
    sa.Column('urbe', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cf'),
    sa.UniqueConstraint('telefono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anagrafiche')
    # ### end Alembic commands ###
