"""added table parentele

Revision ID: c1d1bb5aa373
Revises: de2a6a7447aa
Create Date: 2023-02-05 15:41:16.244884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d1bb5aa373'
down_revision = 'de2a6a7447aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parentele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alunno_id', sa.Integer(), nullable=True),
    sa.Column('genitore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alunno_id'], ['classi.id'], ),
    sa.ForeignKeyConstraint(['genitore_id'], ['genitori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parentele')
    # ### end Alembic commands ###
