"""added table cattedre

Revision ID: de2a6a7447aa
Revises: 10ce7add4f06
Create Date: 2023-02-05 15:39:31.624601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2a6a7447aa'
down_revision = '10ce7add4f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cattedre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.Column('professore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classi.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materie.id'], ),
    sa.ForeignKeyConstraint(['professore_id'], ['professori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cattedre')
    # ### end Alembic commands ###
