"""added table parentele

Revision ID: e8d2d774c69e
Revises: de2a6a7447aa
Create Date: 2023-02-15 22:04:42.519353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d2d774c69e'
down_revision = 'de2a6a7447aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parentele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alunno_id', sa.Integer(), nullable=True),
    sa.Column('genitore_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alunno_id'], ['alunni.id'], ),
    sa.ForeignKeyConstraint(['genitore_id'], ['genitori.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parentele')
    # ### end Alembic commands ###
